### ISSUE TITLE
GeoJSON - Right-hand rule

### ISSUE THREAD

**Issue by dchaffin** [gasparesganga/php-shapefile#13]
I'm using shapefiles from the US Census (e.g. https://www.census.gov/cgi-bin/geo/shapefiles/index.php?year=2017&layergroup=States+%28and+equivalent%29). 

When I parse them with this library, geojsonlint.com says, "Polygons and MultiPolygons should follow the right-hand rule."

Any thoughts on how I can get past this? Is there something in this code I'm missing that may help?

Thanks!

**Comment by gasparesganga** [comment]
Hi, thank you for pointing at this.
Indeed, looking at the RFC 7946 and in particular section [3.1.6](https://tools.ietf.org/html/rfc7946#section-3.1.6) it is stated:
> A linear ring MUST follow the right-hand rule with respect to the
      area it bounds, i.e., **exterior rings are counterclockwise, and
      holes are clockwise**.

Unfortunately, this definition of *inner* and *outer* polygon rings is the opposite of the one used in ESRI Shapefiles. See [the specs](https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf) at page 8:
> The order of vertices or orientation for a ring indicates which side of the ring
is the interior of the polygon.  The neighborhood to the right of an observer walking along
the ring in vertex order is the neighborhood inside the polygon.  Vertices of rings defining
**holes in polygons are in a counterclockwise direction.  Vertices for a single, ringed
polygon are, therefore, always in clockwise order**.

That's actually a reason more why I don't *like* GeoJSON and the way it has been developed, it just goes against many already well-established conventions which have been used for decades and it does so with no apparent reason at all!

This *right hand rule* was something that ESRI engineers thought they required in order to store complex polygons and multipolygons in the binary sequential shapefile (well, they could have come up with a different solution, but it is what it is).
It's worth noting that all major GIS software and spatial extensions for databases have dropped this requirement because it was absolutely redundant when the geometries were stored in a more *modern* fashion.
GeoJSON, on the other hand, decided to enforce this rule, which is absolutely useless, since the format did **NOT** require that to distinguish between inner and outer rings already, they are in different arrays!. But what is worse is that they used the term *right hand rule* meaning the exact opposite of what it normally means, for example with shapefiles, generating a lot of confusion...

Now, after all this loooong information, I will work on that and release a fix addressing this. I just need to think wether it is better to:
1. always enforce this rule only with GeoJSON
2. provide a flag to force clockwise or counterclockwise order with every output format (like PostGIS does)

In the meanwhile, the good piece of news is that you *should* be able to use the current GeoJSON, because I guess the majority of software is not enforcing this rule (which wasn't there in the old GeoJSON specs anyways) and they should be able to accept it. Or, in case you have the option, use WKT instead, until I release the new version of my library.

**Comment by gasparesganga** [comment]
Done [v2.4.2](https://github.com/gasparesganga/php-shapefile/releases/tag/v2.4.2) takes care of that.
Thank you for your feedback!

**Comment by dchaffin** [comment]
Hey, thanks for that!

**Comment by rhabbachi** [comment]
Hey @gasparesganga, I've been using your library for a great effect (thank you for making it open source!). But I'm still getting the "Polygons and MultiPolygons should follow the right-hand rule" on one of the Shapefiles I'm working with:

![image](https://user-images.githubusercontent.com/1914306/48979114-72784980-f0b6-11e8-8bb1-afac1ba27d0b.png)

Those are the shapefiles in question:
[hugo.shp.zip](https://github.com/gasparesganga/php-shapefile/files/2613059/hugo.shp.zip)

Is this a valid bug?

**Comment by gasparesganga** [comment]
Thank you for your feedback.
This is something I have already addressed for the upcoming next major release, v3. There will be a flag to manually reverse the direction of polygons and multipolygons.

You just have to wait a few weeks until v3 is released.

PS: By the way, I think it's not exactly a bug, but a combination of wrong interpetation of the specs, use of the same names for opposite concepts and malformed shapefiles (modern GIS softwares are quite tolerant and "creative" regarding the original specifications). Section 3.1.6 in GeoJSON specs says the direction SHOULD but **not** that it MUST be counterclockwise and then procedes to name it *right-hand-rule* which in many other specs, ESRI shapefiles included, means the opposite. Let's forget about this mess as soon as v3 is released! ;)

**Comment by rhabbachi** [comment]
@gasparesganga  Sounds good!

Is https://github.com/gasparesganga/php-shapefile/tree/v3dev the branch where the fun is happening? I'm willing to test this feature if the current state is usable enough. There is a chance that most if not all the shapefiles I'm / will be dealing with is affected by this specs confusions.

**Comment by gasparesganga** [comment]
Yep, branch v3dev should be fully working at the moment. If you can test it, it would be great to have some feedback, thank you!
There are some undocumented changes (namespace and classes names case change, from ShapeFile* to Shapefile*), but [commit messages](https://github.com/gasparesganga/php-shapefile/commits/v3dev) are quite self explainatory. I think you won't have any trouble in this regard.
In case, feel free to open a new dedicated issue.

I was expecting to release v3 sooner, but work and personal life came in the way.
It is a pretty big change and it will include a *most wanted* feature, you can imagine what it is... let's just keep it as a secret for the moment ;)
